### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by maopenglin** [BoundlessAI/BoundlessKit-iOS#53]
Crashed: SynchronizedArray
0  BoundlessKit                   0x1064d6090 _T012BoundlessKit17SynchronizedArrayC11removeFirstySi_yycSg10completiontFyycfU_AA8BKActionC_Tg5 + 436
1  BoundlessKit                   0x1064a6538 _T0Ieg_IeyB_TR + 36
2  libdispatch.dylib              0x1808b4b24 _dispatch_call_block_and_release + 24
3  libdispatch.dylib              0x1808b4ae4 _dispatch_client_callout + 16
4  libdispatch.dylib              0x1808c373c _dispatch_queue_concurrent_drain + 948
5  libdispatch.dylib              0x1808bf388 _dispatch_queue_invoke$VARIANT$mp + 344
6  libdispatch.dylib              0x1808c1d30 _dispatch_root_queue_drain + 588
7  libdispatch.dylib              0x1808c1a80 _dispatch_worker_thread3 + 120
8  libsystem_pthread.dylib        0x180be7fac _pthread_wqthread + 1176
9  libsystem_pthread.dylib        0x180be7b08 start_wqthread + 4

**Comment by cuddergambino** [comment]
Are you able to reproduce the crash?

**Comment by cuddergambino** [comment]
If you can find a scenario to reproduce the crash, try again with BoundlessKit version 5.5.1 and see if this resolves the issue

**Comment by maopenglin** [comment]
5.5.1 support ios 8.0 ???

**Comment by cuddergambino** [comment]
5.5.1-ios8 does
Please wait a few minutes though, I am releasing 5.5.2 and 5.5.2-ios8 in just a few minutes!

**Comment by cuddergambino** [comment]
@maopenglin please update to version "5.5.2-ios8" if your app needs ios 8.0 support

**Comment by maopenglin** [comment]
@cuddergambino Thank you
